### ISSUE TITLE
what the difference between this repo and main one ?

### ISSUE THREAD

**Issue by Coldzer0** [yuzu-emu/unicorn#12]
Hello

i just saw the commits 
and this repo is really active 

so i want to know what the difference between this repo and main one

thanks

**Comment by lioncash** [comment]
This is a unicorn variant that aims to stay up to date with the changes in qemu's repository. Unicorn, as it is on mainline, isn't capable of executing all the necessary AArch32/AArch64 specifics that are needed for emulating the Switch.
