### ISSUE TITLE
fixing x86 emulation 

### ISSUE THREAD

**Issue by Coldzer0** [yuzu-emu/unicorn#13]
when i try to test your repo and this happen on
```
err = uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
```
Unexpected error in object_property_find() at qom/object.c:907:
Assertion failed: (*errp == NULL), function error_setv, file util/error.c, line 59.
Abort trap: 6

i build with
```
UNICORN_ARCHS="x86" ./make.sh
```

**Comment by Coldzer0** [comment]
i build the lib with

UNICORN_ARCHS="x86" ./make.sh

**Comment by Coldzer0** [comment]
after the last commit 

the

```
err = uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
```
gives  error num 20 = "Insufficient resource (UC_ERR_RESOURCE)"

**Comment by lioncash** [comment]
Reset back a commit and re-pull it. It should initialize fine now.

**Comment by Coldzer0** [comment]
i pull the last fix and now init is ok

but another problem in "uc_mem_write"

i test my own code and get "Invalid memory write (UC_ERR_WRITE_UNMAPPED)"

i thought i make something wrong but this happen in all samples with unicorn 
any use of "uc_mem_write" will give "UC_ERR_WRITE_UNMAPPED"

**Comment by lioncash** [comment]
This should be fixed now.

**Comment by Coldzer0** [comment]
@lioncash 
thanks so much for your work
and yes mem_write & read is ok now 

but when i add hook "UC_HOOK_CODE"  the size param is 0xf1f1f1f1 
it should be the instruction size
 
i tested on my project and unicorn examples both give me the same value for size "0xf1f1f1f1"

**Comment by Coldzer0** [comment]
@lioncash 

and another thing i notice is

when the code enter an call like 

0x40155A  : call 0x4093d0
0x4093d0 : ret
0x40155F : mov edi,edi

this should go like this

0x40155A  : call 0x4093d0
0x4093d0 :     ret
0x40155F  : mov edi,edi

but with your code it go like

0x40155A
0x40155A
0x40155A
then an mem error

Missing memory is being WRITE at 0x10FFFC, data size = 4, data value = "0x40155F"

as you can see the ret value "0x40155F" is also static like the size and the EIP

so i think maybe the registers didn't updated inside the hook or maybe something wrong before the hook

cuz EIP and ESP will be same values after any "call instruction" 
and size is already set to 0xf1f1f1f1 
no matter the instruction is 

hope this will help to find the problem
again thanks for your work
really appreciate it

**Comment by Coldzer0** [comment]
i think uc_mem_read act the same like uc_mem_write
it gives "UC_ERR_READ_UNMAPPED"

i tested with this code

```python
import unicorn
import unicorn.x86_const as x86

sc = (
    "dbd0d97424f45fb8e67741bc31c9b15831471a03471a83c704e2138ba93edb742"
    "a5f52911b5f00d10c6f43b7a004012c32688d43f3c7eb6a047bcfed868603ceb7"
    "48560fffb59a5da8b20872dd8f90f9ad1e901e6520b1b0fd7b1132d1f7182c363"
    "dd3c78cc9e201dd32486cd1c091a8d63ae4c024c6fe16561c8b8cf0d72b69003b"
    "adfa0ef0baa512076fde2f8c8e31a6d6b495e28dd58c4e63eacf30dc4e9bdd09e"
    "3c689a39e8c4954170424cd83bef47a0d38fa50609d5708d1720bc6ef22d2b1f0"
    "1e77ed64a22b4210ffda64e0175064e0e7460ca6d7ad862648a641aff7f0917a8"
    "e3b3eec91f12168c2a6f227b61e9d2c6db1664d5b5bf2bb3b0c8388c3cc0a0ea9"
    "c85ca43187344d08b94352419618ff394ff7d2bb777cd31102425e90423679cca"
    "c0ddb5bb2bb7124244495a4b42c95a4f4acc6ccac08bbe9b284a8a11fae2912c8"
    "b0959d08e283f51a92a2e4e44f31286ebdb2ae8efe4170e5e511b2590ed4cb993"
    "1614311fda3c8b573d46323595f0c85c5fe98bc05"
).decode("hex")

print unicorn

def main():
    uc = unicorn.Uc(unicorn.UC_ARCH_X86, unicorn.UC_MODE_32)
    uc.mem_map(0x1000, 0x2000)
    uc.mem_write(0x1000, sc)
    uc.reg_write(x86.UC_X86_REG_ESP, 0x2000)
    uc.emu_start(0x1000, 0, count=0x166)
    out = uc.mem_read(0x1000, 0x2000)

    for x in xrange(len(sc)):
        print "0x%08x: 0x%02x => 0x%02x" % (x, ord(sc[x]), out[x])
    print str(out)

if __name__ == "__main__":
    main()
```

**Comment by lioncash** [comment]
With 2922a254798cf90a2b74393db59e422affadee0d, instruction sizes should report properly in the code hooks.

As a general note, if something seems wrong in x86 emulation, it probably is. This fork was only primarily aimed at working with ARM/AArch64-related targets, so the others are likely lacking in proper functionality.

**Comment by lioncash** [comment]
fffc31e7e2595cd19c32b361fed769cae3277dc6 should restore synchronization of the EIP register value when read/write callbacks are set.

**Comment by Coldzer0** [comment]
@lioncash 

i think there's a lot to do in x86

so i've suggestion 
if you can make a video explain the important functions used by Unicorn 
and some info about the flow of the code starting from "uc_emu_start" 

i know this will take time 
but will help to make ppl contribute more and helping with the code
and i really want to help as much as possible

**Comment by lioncash** [comment]
I legitimately don't have the time to make a video about Unicorn, sorry. This would be more suited for the devs that actually work on Unicorn in the main repository. We're just people that use Unicorn as a fuzzer for AArch64 code and an interpreter for when our JIT doesn't handle certain AArch64 instructions.

**Comment by Coldzer0** [comment]
@lioncash 

it's ok 

so is there any deed to continu fixing the x86 ?

if yes can you please check my last problem in my comment
https://github.com/yuzu-emu/unicorn/issues/13#issuecomment-418208924

**Comment by lioncash** [comment]
Yes. I'll take a look when I have time tomorrow.

**Comment by Coldzer0** [comment]
@lioncash 
thanks so much and 1 more thing

this problem really is important to solve
https://github.com/unicorn-engine/unicorn/issues/820

i'm working on Malware Sandbox for x86 PE files
with JS as scripting layer for the easy of code and handling everything 

here's example for what i did for far (this's only i function hook) i did almost 200+- 

```javascript
var GetModuleFileName = new ApiHook();
/*
DWORD WINAPI GetModuleFileName(
  _In_opt_ HMODULE hModule,
  _Out_    LPTSTR  lpFilename,
  _In_     DWORD   nSize
);
*/
GetModuleFileName.OnCallBack = function (Emu, API, ret) {

    Emu.pop(); // ret
    
    var hModule    = Emu.isx64 ? Emu.ReadReg(REG_RCX) : Emu.pop();
    var lpFilename = Emu.isx64 ? Emu.ReadReg(REG_RDX) : Emu.pop();
    var nSize      = Emu.isx64 ? Emu.ReadReg(REG_R8D) : Emu.pop();

    var mName = Emu.GetModuleName(hModule); // GetModuleName is implemented in the Cmulator to get Module name from handle
    var Path  = 'C:\\folder\\' + mName;

    Emu.HexDump(lpFilename,32); // hex dump view so we can check before writing 
    var len = API.isWapi ? Emu.WriteStringW(lpFilename,Path) : Emu.WriteStringA(lpFilename,Path);
    Emu.HexDump(lpFilename,32); // hex dump view so we can check after writing 
    
    print("GetModuleFileName{0}(0x{1}, 0x{2}, 0x{3}) = '{4}'".format(
        API.IsWapi ? 'W' : 'A',
        hModule.toString(16),
        lpFilename.toString(16),
        nSize.toString(16),
        Path
    ));

    // MS Docs : the return value is the length of the string
    Emu.SetReg(Emu.isx64 ? REG_RAX : REG_EAX, len); 
    Emu.SetReg(Emu.isx64 ? REG_RIP : REG_EIP, ret);
    return true; // true if you handle it false if you want Emu to handle it and set PC .
};

GetModuleFileName.install('kernel32.dll', 'GetModuleFileNameA');
GetModuleFileName.install('kernel32.dll', 'GetModuleFileNameW');
```
and here's small example running small program check for Debugger then show Message & Exit

```
Compiled on      : 2018/09/04 - 01:18:25
Target CPU       : i386 & x86_x64
Unicorn Engine   : v1.0 
Cmulator         : v0.1

"malxx.exe" is : x32
Mapping the File ..

[+] Unicorn Init done  .
[+] Segments & (TIB - PEB) Init Done .
[√] Set Hooks
[√] PE Mapped to Unicorn
[√] PE Written to Unicorn

[---------------------------------------]
[            Fixing PE Imports          ]

[*] File Name  : malxx.exe

[>] malxx.exe Import : user32.dll

"MessageBoxA"
  Real rva: 0x405050   - New : 0x702FFD1E
"ExitProcess"
  Real rva: 0x405058   - New : 0x70197A10
"IsDebuggerPresent"
  Real rva: 0x40505C   - New : 0x70194A5D
[---------------------------------------]

loading JS Hook Module : ./hooks/const.js
loading JS Hook Module : ./hooks/ntdll.js
loading JS Hook Module : ./hooks/kernel32.js
loading JS Hook Module : ./hooks/kernel32_threads.js
loading JS Hook Module : ./hooks/kernek32_strings.js
loading JS Hook Module : ./hooks/user32.js
loading JS Hook Module : ./hooks/advapi32.js
loading JS Hook Module : ./hooks/urlmon.js
loading JS Hook Module : ./hooks/c_runtime.js

[>] Run malxx.exe

0x4010A0  call 0x401070
0x401070  call 0x401080
0x401080  ret 
0x401075  call 0x401030
0x401030  push ebp
0x401031  mov ebp, esp
0x401033  call 0x401020
0x401020  jmp dword ptr [0x40505c]

[+] Call to "kernel32.dll.IsDebuggerPresent"
[#] Will Return to : 0x401038

====================== CallBack to JS ==========================

IsDebuggerPresent = 0

================================================================

0x401038  test al, al
0x40103A  je 0x401053
0x401053  push 0
0x401055  mov eax, 0x403010
0x40105A  push eax
0x40105B  mov eax, 0x403014
0x401060  push eax
0x401061  push 0
0x401063  call 0x401000
0x401000  jmp dword ptr [0x405050]

[+] Call to "user32.dll.MessageBoxA"
[#] Will Return to : 0x401068

====================== CallBack to JS ==========================

MessageBoxA(0, 'Hi From Main Thread ..', ';)', 0) 

================================================================

0x401068  mov al, dl
0x40106A  leave 
0x40106B  ret 
0x40107A  call 0x401090
0x401090  push 0
0x401092  call 0x401010
0x401010  jmp dword ptr [0x405058]

[+] Call to "kernel32.dll.ExitProcess"
[#] Will Return to : 0x401097

====================== CallBack to JS ==========================

ExitProcess(0)

================================================================


Cmulator Stop >> last Error : OK (UC_ERR_OK)
```

i did a lot of work on it 
mapping the file and exports imports everything works fine
tested on many files x32 & x64 everything works fine 
and the project will be Open Source , i'll upload it on 9/9 🎂 as it's my birthday :V 


but with the problem i mention if the file has xor decryption loop near EIP or RIP 
it will act strange as explained on the issue 

again i really appreciate your work and if there's any thing i can help with i'll do
thanks

**Comment by Coldzer0** [comment]
Hello @lioncash 
any news about this https://github.com/unicorn-engine/unicorn/issues/820 ?

thanks

**Comment by lioncash** [comment]
No, I've been busy as of late

**Comment by Guy1524** [comment]
Looks like compilation of the x86 target is currently broken with:

```
unicorn/qemu/target/i386/fpu_helper.c:301:5: error: 'val' undeclared (first use in this function)
  301 |     val = floatx80_to_int32(ST0, &env->fp_status);```

**Comment by Guy1524** [comment]
[diff.txt](https://github.com/yuzu-emu/unicorn/files/5189563/diff.txt)

I hacked together these compilation fixes.
