### ISSUE TITLE
Multiple definitions of `vfp_expand_imm`

### ISSUE THREAD

**Issue by MerryMage** [yuzu-emu/unicorn#19]
Multiple definitions of `vfp_expand_imm` when compiling multiple arm frontends after b2dc290454f3a223866d3e16b2c3716cb6ce2cfa.

**Comment by lioncash** [comment]
Does 38136cb5f15489a53098f0517dbeb9954a1b46d0 resolve this?

**Comment by MerryMage** [comment]
Yes.
