### ISSUE TITLE
cutils.c

### ISSUE THREAD

**Issue by br8shine** [yuzu-emu/unicorn#22]
`./qemu/util/cutils.c`
has
> #include <sys/mman.h>

It's partially breaks windows compilation. What is it for?

**Comment by lioncash** [comment]
This fork will not build on Windows at all due to the use of GCC specifics extensions being used in upstream qemu.

**Comment by br8shine** [comment]
I was able to build with msys2 mingw (cross build for win64) but it still requires to remove the line with that include meantioned above. It has no side effects.
